# This workflow builds and deploys an ASP.NET Core app to Azure Web App when a commit is pushed to the Dev branch.
# Prerequisites:
# 1. Create the Azure Web App in the Azure portal.
# 2. Download the Publish Profile from your Azure Web App (Overview -> Get Publish Profile).
# 3. Add a GitHub secret named AZURE_WEBAPP_PUBLISH_PROFILE with the content of the publish profile.
# 4. Update AZURE_WEBAPP_NAME with your Azure Web App name.

name: Build and Deploy ASP.NET Core App to Azure Web App

env:
  AZURE_WEBAPP_NAME: your-app-name              # Replace with your Azure Web App name
  AZURE_WEBAPP_PACKAGE_PATH: '.'               # Path to your app, default is repo root
  DOTNET_VERSION: '8.0.x'                      # Using .NET 8

on:
  push:
    branches: [ "Dev" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet Packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --configuration Release --no-restore

      - name: Publish Application
        run: dotnet publish --configuration Release --output ${{env.DOTNET_ROOT}}/myapp

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
